### ISSUE TITLE
Async calls break the context

### ISSUE THREAD

**Issue by MaxStalker** [ealush/context#9]
Calling and `awaiting` any async function breaks the value of context.
Should this work properly or it's a known issue? :)

I've created an example on Codesandbox here:
https://codesandbox.io/s/broken-async-context-qy1jf?file=/src/index.js

**Comment by ealush** [comment]
Hey @MaxStalker, thanks for reaching out.

Yes, this is known and expected behavior. Context is a synchronous context propagation tool that completely relies on the synchronous nature of function calls in JS - this is exactly what allows context to run, it should probably appear in the docs.

## Why this happens? - (or how context works)
The way context works is quite simple. When you run your context call, it takes your values, and places them in the [context storage object](https://github.com/ealush/context/blob/master/src/index.ts#L4). When your function finishes running, the context is cleared.

![image](https://user-images.githubusercontent.com/11255103/135322099-dfa4aebc-888f-427b-ad30-d7e769ec7d9f.png)

The reason the context is cleared after its run is so that items can't override one another. Assume you have two running the same async function twice, and it writes to the context, expecting to read the value somewhere down the line. Now you have two competing consumers of this single resource, and one eventually get the wrong value since they both read from and write to the same place.

## But my function is still running. Why did the context clear?

The async parts of your function are actually not executed along with your sync code, and even though you "await" it, the browser carries on and allows other code to run in between instead of blocking execution until your async code is complete.

## Ok, so what do I do?

There are multiple strategies of handling async functions with context.

1. Pulling your values from context right before your async call
This is the most obvious and easiest to achieve, though not always what you need. The basic idea is that you take whatever you need from the context when it is still available to you.
https://github.com/ealush/vest/blob/e16b4f9f614487c7c1f66d2a4d7d39df80e87f52/packages/vest/src/core/test/runAsyncTest.ts#L19
In this example I take `stateRef` from the context so I can later use it in an async function.

2. context.bind or context.run your async function to the context you extracted
This is the next logical step - you have a function that you know should run later with your context. You can bind your context to it for delayed execution. When your function runs later down the line within your asynchronous code, internally it will still have access to whatever you bound to it.
https://github.com/ealush/vest/blob/vest-4-integration-branch/packages/vest/src/core/test/runAsyncTest.ts#L20-L38
